#!/bin/bash

[ $# -lt 1 ] && echo "$0 <path/to/folder>" && exit -1

echo "[DETOX]"
sudo /usr/local/bin/detox -r -s lower "$1"

echo "[FIND VIDS]"
sudo find "$1" -type f -regex ".*\(mp4\|mkv\|3gp\|xa\|wav\|dts\|ty\|tta\|tac\|ts\|mpg\|ra\|ram\|rm\|rv\|rmbv\|ogm\|ogg\|nut\|nsv\|nsc\|mpg\|mp3\|mp2\|mp4\|mov\|mka\|flv\|avi\|au\|asf\|wmv\|a52\|dts\|aac\|flac\|dv\|vid)" -exec mv {} "$1" \;

echo "[RM EVERYTHING ELSE]"
sudo find "$1" -type d -exec rm -rf {} \;

echo "[RM METADATA]"
sudo exiftool -r -overwrite_original -all= "$1"

echo "[SET USER AND ACL]"
sudo chown -R transmission:fer "$1" && sudo chmod -R g+w "$1"
